# -*- coding: utf-8 -*-
"""Séance_04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKhBqxhqt1kLU_OfXmDK6zG7uKNtWeIB
"""

import numpy as np
import pandas as pd
import scipy
import scipy.stats as stats

#https://docs.scipy.org/doc/scipy/reference/stats.html


dist_names = ['norm', 'beta', 'gamma', 'pareto', 't', 'lognorm', 'invgamma', 'invgauss',  'loggamma', 'alpha', 'chi', 'chi2', 'bradford', 'burr', 'burr12', 'cauchy', 'dweibull', 'erlang', 'expon', 'exponnorm', 'exponweib', 'exponpow', 'f', 'genpareto', 'gausshyper', 'gibrat', 'gompertz', 'gumbel_r', 'pareto', 'pearson3', 'powerlaw', 'triang', 'weibull_min', 'weibull_max', 'bernoulli', 'betabinom', 'betanbinom', 'binom', 'geom', 'hypergeom', 'logser', 'nbinom', 'poisson', 'poisson_binom', 'randint', 'zipf', 'zipfian']

print(dist_names)

#les distributions statistiques de variables discrètes suivantes :
from matplotlib import pyplot as plt

def plot_discrete_distribution(dist, x_range, title, **params):
    """Visualise une distribution discrète."""
    x = np.arange(*x_range)
    pmf = dist.pmf(x, **params)

    plt.figure(figsize=(10, 6))
    plt.bar(x, pmf, alpha=0.7, edgecolor='black')
    plt.title(title, fontsize=14, fontweight='bold')
    plt.xlabel('x', fontsize=12)
    plt.ylabel('Probabilité', fontsize=12)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

# Loi de Dirac (cas particulier : masse en un point)
def plot_dirac(loc=5):
    """Visualise la loi de Dirac."""
    x = np.arange(0, 11)
    y = np.zeros_like(x, dtype=float)
    y[loc] = 1.0

    plt.figure(figsize=(10, 6))
    plt.bar(x, y, alpha=0.7, edgecolor='black')
    plt.title(f'Loi de Dirac (masse en x={loc})', fontsize=14, fontweight='bold')
    plt.xlabel('x', fontsize=12)
    plt.ylabel('Probabilité', fontsize=12)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

# Loi uniforme discrète
def plot_uniform_discrete(low=1, high=10):
    """Visualise la loi uniforme discrète."""
    plot_discrete_distribution(
        stats.randint, (low, high + 1),
        f'Loi uniforme discrète [{low}, {high}]',
        low=low, high=high + 1
    )

# Loi binomiale
def plot_binomial(n=20, p=0.5):
    """Visualise la loi binomiale."""
    plot_discrete_distribution(
        stats.binom, (0, n + 1),
        f'Loi binomiale (n={n}, p={p})',
        n=n, p=p
    )

# Loi de Poisson
def plot_poisson_discrete(mu=5):
    """Visualise la loi de Poisson (variable discrète)."""
    plot_discrete_distribution(
        stats.poisson, (0, mu * 3 + 1),
        f'Loi de Poisson (λ={mu})',
        mu=mu
    )

# Loi de Zipf-Mandelbrot
def plot_zipf(a=2.0, n=20):
    """Visualise la loi de Zipf."""
    plot_discrete_distribution(
        stats.zipf, (1, n + 1),
        f'Loi de Zipf (a={a})',
        a=a
    )

#les distributions statistiques de variables continues suivantes

def plot_continuous_distribution(dist, x_range, title, **params):
    """Visualise une distribution continue."""
    x = np.linspace(*x_range, 500)
    pdf = dist.pdf(x, **params)

    plt.figure(figsize=(10, 6))
    plt.plot(x, pdf, linewidth=2, color='steelblue')
    plt.fill_between(x, pdf, alpha=0.3, color='steelblue')
    plt.title(title, fontsize=14, fontweight='bold')
    plt.xlabel('x', fontsize=12)
    plt.ylabel('Densité de probabilité', fontsize=12)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

# Loi de Poisson (approximation continue)
def plot_poisson_continuous(mu=5):
    """Visualise l'approximation continue de la loi de Poisson."""
    x = np.arange(0, mu * 3 + 1)
    pmf = stats.poisson.pmf(x, mu=mu)

    plt.figure(figsize=(10, 6))
    plt.plot(x, pmf, 'o-', linewidth=2, markersize=6, color='steelblue')
    plt.fill_between(x, pmf, alpha=0.3, color='steelblue')
    plt.title(f'Loi de Poisson continue (λ={mu})', fontsize=14, fontweight='bold')
    plt.xlabel('x', fontsize=12)
    plt.ylabel('Probabilité', fontsize=12)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.show()

# Loi normale
def plot_normal(mu=0, sigma=1):
    """Visualise la loi normale."""
    x_range = (mu - 4*sigma, mu + 4*sigma, 500)
    plot_continuous_distribution(
        stats.norm, x_range,
        f'Loi normale (μ={mu}, σ={sigma})',
        loc=mu, scale=sigma
    )

# Loi log-normale
def plot_lognormal(s=0.5, scale=1):
    """Visualise la loi log-normale."""
    plot_continuous_distribution(
        stats.lognorm, (0, 5, 500),
        f'Loi log-normale (s={s}, scale={scale})',
        s=s, scale=scale
    )

# Loi uniforme
def plot_uniform_continuous(a=0, b=1):
    """Visualise la loi uniforme continue."""
    plot_continuous_distribution(
        stats.uniform, (a - 0.5, b + 0.5, 500),
        f'Loi uniforme [{a}, {b}]',
        loc=a, scale=b - a
    )

# Loi du chi-carré
def plot_chi2(df=5):
    """Visualise la loi du chi-carré."""
    plot_continuous_distribution(
        stats.chi2, (0, df * 3, 500),
        f'Loi du χ² (df={df})',
        df=df
    )

# Loi de Pareto
def plot_pareto(b=2.5, scale=1):
    """Visualise la loi de Pareto."""
    plot_continuous_distribution(
        stats.pareto, (0, 5, 500),
        f'Loi de Pareto (b={b})',
        b=b, scale=scale
    )

#2. Faire des fonctions (informatiques) pour calculer la moyenne et l’écart type des distributions précédentes.

def compute_stats(dist, dist_type='continuous', **params):
    """Calcule la moyenne et l'écart-type d'une distribution."""
    mean, var = dist.stats(**params, moments='mv')
    std = np.sqrt(var)
    return {
        'moyenne': float(mean),
        'ecart_type': float(std),
        'variance': float(var)
    }

import matplotlib.pyplot as plt

#Exemples d'utilisation

if __name__ == "__main__":
    print("=" * 60)
    print("VISUALISATION DES DISTRIBUTIONS STATISTIQUES")
    print("=" * 60)

    # Distributions discrètes
    print("\n1. DISTRIBUTIONS DISCRÈTES\n")

    plot_dirac(loc=5)
    plot_uniform_discrete(low=1, high=10)
    plot_binomial(n=20, p=0.5)
    plot_poisson_discrete(mu=5)
    plot_zipf(a=2.0, n=20)

    # Distributions continues
    print("\n2. DISTRIBUTIONS CONTINUES\n")

    plot_poisson_continuous(mu=5)
    plot_normal(mu=0, sigma=1)
    plot_lognormal(s=0.5, scale=1)
    plot_uniform_continuous(a=0, b=1)
    plot_chi2(df=5)
    plot_pareto(b=2.5, scale=1)

#Fonctions (informatiques) pour calculer la moyenne et l’écart type des distributions précédentes
print("\n3. STATISTIQUES DES DISTRIBUTIONS\n")

distributions = {
    'Uniforme discrète': (stats.randint, {'low': 1, 'high': 11}),
    'Binomiale': (stats.binom, {'n': 20, 'p': 0.5}),
    'Poisson': (stats.poisson, {'mu': 5}),
    'Normale': (stats.norm, {'loc': 0, 'scale': 1}),
    'Log-normale': (stats.lognorm, {'s': 0.5}),
    'Chi-carré': (stats.chi2, {'df': 5}),
    'Pareto': (stats.pareto, {'b': 2.5})
}

for name, (dist, params) in distributions.items():
    stats_dict = compute_stats(dist, **params)
    print(f"{name:20} → μ={stats_dict['moyenne']:.4f}, "
          f"σ={stats_dict['ecart_type']:.4f}")

print("\n" + "=" * 60)