# -*- coding: utf-8 -*-
"""Séance_06

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qJjHVH47XVX48wNQoWx83Y-xrjp1KlPn
"""

#coding:utf8

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import scipy.stats
import math

#Fonction pour ouvrir les fichiers
def ouvrirUnFichier(nom):
    with open(nom, "r") as fichier:
        contenu = pd.read_csv(fichier)
    return contenu

#Fonction pour convertir les données en données logarithmiques
def conversionLog(liste):
    log = []
    for element in liste:
        log.append(math.log(element))
    return log

#Fonction pour trier par ordre décroissant les listes (îles et populations)
def ordreDecroissant(liste):
    liste.sort(reverse = True)
    return liste

#Fonction pour obtenir le classement des listes spécifiques aux populations
def ordrePopulation(pop, etat):
    ordrepop = []
    for element in range(0, len(pop)):
        if np.isnan(pop[element]) == False:
            ordrepop.append([float(pop[element]), etat[element]])
    ordrepop = ordreDecroissant(ordrepop)
    for element in range(0, len(ordrepop)):
        ordrepop[element] = [element + 1, ordrepop[element][1]]
    return ordrepop

#Fonction pour obtenir l'ordre défini entre deux classements (listes spécifiques aux populations)
def classementPays(ordre1, ordre2):
    classement = []
    if len(ordre1) <= len(ordre2):
        for element1 in range(0, len(ordre2) - 1):
            for element2 in range(0, len(ordre1) - 1):
                if ordre2[element1][1] == ordre1[element2][1]:
                    classement.append([ordre1[element2][0], ordre2[element1][0], ordre1[element2][1]])
    else:
        for element1 in range(0, len(ordre1) - 1):
            for element2 in range(0, len(ordre2) - 1):
                if ordre2[element2][1] == ordre1[element1][1]:
                    classement.append([ordre1[element1][0], ordre2[element2][0], ordre1[element][1]])
    return classement

#Partie sur les îles
def ouvrirUnFichier(nom):
    with open(nom, "r", encoding="utf-8") as fichier:
        contenu = pd.read_csv(fichier)
    return contenu

iles = pd.DataFrame(
    ouvrirUnFichier("./data/island-index.csv"))

#Attention ! Il va falloir utiliser des fonctions natives de Python dans les fonctions locales que je vous propose pour faire l'exercice. Vous devez caster l'objet Pandas en list().


#Partie sur les populations des États du monde
#Source. Depuis 2007, tous les ans jusque 2025, M. Forriez a relevé l'intégralité du nombre d'habitants dans chaque États du monde proposé par un numéro hors-série du monde intitulé États du monde. Vous avez l'évolution de la population et de la densité par année.
iles = pd.DataFrame(
    ouvrirUnFichier("./data/Le-Monde-HS-Etats-du-monde-2007-2025.csv"))

#Attention ! Il va falloir utiliser des fonctions natives de Python dans les fonctions locales que je vous propose pour faire l'exercice. Vous devez caster l'objet Pandas en list().

#PARTIE 1 : ANALYSE DES ÎLES =====

print("="*60)
print("PARTIE 1 : LOI RANG-TAILLE DES ÎLES")
print("="*60)

# 2. Ouvrir le fichier des îles
iles = pd.DataFrame(
    ouvrirUnFichier("./data/island-index.csv"))

print(iles.columns.tolist())

# 3. Isoler la colonne Surface et ajouter les continents (cast en float)
surfaces = list(iles['Surface (km²)'])
surfaces.extend([
    float(85545323),  # Asie / Afrique / Europe
    float(37856841),  # Amérique
    float(7768030),   # Antarctique
    float(7605049)    # Australie
])

# 4. Ordonner par ordre décroissant avec la fonction locale
surfaces_ordonnees = ordreDecroissant(surfaces.copy())

var = [float(x) for x in list(iles['Surface (km²)']) + [85545323, 37856841, 7768030, 7605049]]
tailles = ordreDecroissant(var)
rangs = list(range(1, len(tailles) + 1))

# 5. Visualiser la loi rang-taille (échelle normale)
plt.figure(figsize=(8, 6))
plt.plot(rangs, tailles, marker='o')
plt.title("Loi rang-taille")
plt.xlabel("Rang")
plt.ylabel("Surface (km²)")
plt.grid(True)
plt.tight_layout()
plt.show()

from pathlib import Path

IMG_DIR = Path("images")
IMG_DIR.mkdir(exist_ok=True)

# 6. Conversion en échelle logarithmique avec la fonction locale
plt.figure(figsize=(8, 6))
plt.plot(rangs, conversionLog(tailles), marker='o')
plt.title("Loi rang-taille")
plt.xlabel("Rang")
plt.ylabel("Surface (km²)")
plt.grid(True)
plt.tight_layout()
plt.show()

print(f"✓ Graphique sauvegardé dans {IMG_DIR}/loi_rang_taille_iles.png")

# 7. Réponse : Est-il possible de faire un test sur les rangs ?
"""
RÉPONSE QUESTION 7 :
Non, il n'est PAS possible de faire un test de corrélation des rangs avec une seule variable.
Les tests de Spearman et Kendall nécessitent DEUX variables ordinales à comparer.
Ici, nous avons uniquement la surface des îles classées par rang (une seule variable).
Pour faire un test, il faudrait comparer ce classement avec un autre classement
(par exemple : surface vs trait de côte).
"""
print("\n--- Réponse question 7 ---")
print("Non, impossible de faire un test sur les rangs avec UNE seule variable.")
print("Les tests de Spearman/Kendall nécessitent DEUX classements à comparer.")

# 9. Ouvrir le fichier des populations
iles = pd.DataFrame(
    ouvrirUnFichier("./data/Le-Monde-HS-Etats-du-monde-2007-2025.csv"))

# 10. Isoler les colonnes nécessaires (cast en list pour fonctions locales)
monde = pd.DataFrame(ouvrirUnFichier("./data/Le-Monde-HS-Etats-du-monde-2007-2025.csv"))
etats = list(monde['État'])
pop_2007 = list(monde['Pop 2007'])
pop_2025 = list(monde['Pop 2025'])
densite_2007 = list(monde['Densité 2007'])
densite_2025 = list(monde['Densité 2025'])

# 11. Ordonner avec la fonction locale ordrePopulation()
ordre_pop_2007 = ordrePopulation(pop_2007, etats)
ordre_pop_2025 = ordrePopulation(pop_2025, etats)
ordre_den_2007 = ordrePopulation(densite_2007, etats)
ordre_den_2025 = ordrePopulation(densite_2025, etats)

# 12. Préparer les comparaisons avec classementPays()
classement_pop = classementPays(ordre_pop_2007, ordre_pop_2025)
classement_den = classementPays(ordre_den_2007, ordre_den_2025)
# Trier les résultats
classement_pop.sort()
classement_den.sort()

# 13. Isoler les deux colonnes avec une boucle
rangs_pop_2007 = []
rangs_pop_2025 = []
for item in classement_pop:
    rangs_pop_2007.append(item[0])
    rangs_pop_2025.append(item[1])

rangs_den_2007 = []
rangs_den_2025 = []
for item in classement_den:
    rangs_den_2007.append(item[0])
    rangs_den_2025.append(item[1])

# 14. Calculer les coefficients avec scipy.stats
print("\n--- POPULATIONS 2007 vs 2025 ---")
spearman_pop, p_spearman_pop = scipy.stats.spearmanr(rangs_pop_2007, rangs_pop_2025)
kendall_pop, p_kendall_pop = scipy.stats.kendalltau(rangs_pop_2007, rangs_pop_2025)

print(f"Coefficient de Spearman (ρ): {spearman_pop:.4f} (p-value: {p_spearman_pop:.4e})")
print(f"Coefficient de Kendall (τ): {kendall_pop:.4f} (p-value: {p_kendall_pop:.4e})")

print("\n--- DENSITÉS 2007 vs 2025 ---")
spearman_den, p_spearman_den = scipy.stats.spearmanr(rangs_den_2007, rangs_den_2025)
kendall_den, p_kendall_den = scipy.stats.kendalltau(rangs_den_2007, rangs_den_2025)

print(f"Coefficient de Spearman (ρ): {spearman_den:.4f} (p-value: {p_spearman_den:.4e})")
print(f"Coefficient de Kendall (τ): {kendall_den:.4f} (p-value: {p_kendall_den:.4e})")

#BONUS : ANALYSES SUPPLÉMENTAIRES

print("\n" + "="*60)
print("BONUS : ANALYSES APPROFONDIES")
print("="*60)

# BONUS 1 : Fonction locale pour analyser les rangs (factorisation)
def analyserRangs(liste1, liste2, nom1="Variable 1", nom2="Variable 2"):
    """Calcule et affiche les coefficients de Spearman et Kendall."""
    rho, p_rho = scipy.stats.spearmanr(liste1, liste2)
    tau, p_tau = scipy.stats.kendalltau(liste1, liste2)

    print(f"\n=== {nom1} vs {nom2} ===")
    print(f"Spearman (ρ): {rho:.4f} (p: {p_rho:.4e})")
    print(f"Kendall (τ): {tau:.4f} (p: {p_tau:.4e})")

    return rho, tau

import pandas as pd
from scipy.stats import spearmanr

#BONUS 2 : Proposition d'un  algorithme et un code pour comparer le classement obtenu avec les surfaces et un autre classement obtenu avec les traits de côte en utilisant le coefficient decorrélation et la concordans des rangs.
# Lire le fichier CSV
file_path = "./data/island-index.csv"
iles = pd.read_csv(file_path)

# Afficher les colonnes pour vérifier les noms exacts
print(iles.columns)

# Supposons que les colonnes soient nommées 'Surface (km²)' et 'Coastline (km)'
# Remplacez ces noms par ceux qui apparaissent dans votre DataFrame
surface_col = 'Surface (km²)'
coastline_col = 'Trait de côte (km)' # Corrected column name based on iles.columns

# Extraire les données nécessaires
surfaces = iles[surface_col]
traits_cote = iles[coastline_col]
island_names = iles['Toponyme']  # Assuming 'Toponyme' is the column for island names

# Créer des classements
rank_surfaces = surfaces.rank(ascending=False)
rank_traits_cote = traits_cote.rank(ascending=False)

# Afficher les classements
print("\nClassement par Surface:")
print(rank_surfaces)

print("\nClassement par Trait de Côte:")
print(rank_traits_cote)

# Calculer le coefficient de corrélation de Spearman
correlation, p_value = spearmanr(rank_surfaces.dropna(), rank_traits_cote.dropna()) # Handle NaN values

print(f"\nCoefficient de corrélation de Spearman: {correlation:.3f}")
print(f"P-value: {p_value:.3f}")

# Analyser la concordance des rangs
if correlation > 0.7:
    print("Il y a une forte concordance entre les classements.")
elif correlation > 0.3:
    print("Il y a une concordance modérée entre les classements.")
else:
    print("Il y a une faible concordance entre les classements.")

#BONUS 3 :  factoriser le code d’analyse des classements sous la forme d’une fonction renvoyant les coefficients de corrélation des rangs et la concordances des rangs

print("\n--- BONUS : Évolution temporelle 2007-2025 ---")

annees = list(range(2007, 2026))
coefficients_spearman = []
coefficients_kendall = []

for i in range(len(annees) - 1):
    col_pop1 = f'Pop {annees[i]}'
    col_pop2 = f'Pop {annees[i+1]}'

    if col_pop1 in monde.columns and col_pop2 in monde.columns:
        pop1 = list(monde[col_pop1])
        pop2 = list(monde[col_pop2])

        # Utiliser les fonctions locales
        ordre1 = ordrePopulation(pop1, etats)
        ordre2 = ordrePopulation(pop2, etats)
        classement = classementPays(ordre1, ordre2)
        classement.sort()

        # Isoler les rangs avec boucle
        rangs1 = []
        rangs2 = []
        for item in classement:
            rangs1.append(item[0])
            rangs2.append(item[1])

        # Analyser avec fonction locale
        rho, tau = analyserRangs(rangs1, rangs2,
                                  f"Pop {annees[i]}", f"Pop {annees[i+1]}")
        coefficients_spearman.append(rho)
        coefficients_kendall.append(tau)

#BONUS 3 : faire un algorithme et un code permettant d’analyser la concordance des rangs de l’ensemble des classements annuels de 2007 à 2025

# Visualisation de l'évolution
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(range(2007, 2025), coefficients_spearman, 'o-', linewidth=2, markersize=6)
plt.xlabel('Année (transition n → n+1)')
plt.ylabel('Coefficient de Spearman (ρ)')
plt.title('Corrélation des rangs (2007-2025)')
plt.grid(True, alpha=0.3)
plt.ylim(0.95, 1.0)

plt.subplot(1, 2, 2)
plt.plot(range(2007, 2025), coefficients_kendall, 'o-', linewidth=2, markersize=6, color='orange')
plt.xlabel('Année (transition n → n+1)')
plt.ylabel('Coefficient de Kendall (τ)')
plt.title('Concordance des rangs (2007-2025)')
plt.grid(True, alpha=0.3)
plt.ylim(0.90, 1.0)

plt.tight_layout()
plt.savefig(IMG_DIR / "evolution_coefficients.png", dpi=150, bbox_inches='tight')
plt.close()

print(f"\n✓ Graphique sauvegardé dans {IMG_DIR}/evolution_coefficients.png")