# -*- coding: utf-8 -*-
"""Séance_03

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_oQC60YxJkSm9JpIottehBV4T4XMlgVV
"""

#coding:utf8

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Source des données : https://www.data.gouv.fr/datasets/election-presidentielle-des-10-et-24-avril-2022-resultats-definitifs-du-1er-tour/

# Sources des données : production de M. Forriez, 2016-2023

#Question 4 : Repérer l'instruction with

with open("./data/resultats-elections-presidentielles-2022-1er-tour.csv", "r", encoding="utf-8") as fichier:
    contenu = pd.read_csv(fichier)

with open("./data/island-index.csv", "r", encoding="utf-8") as fichier:
    contenu = pd.read_csv(fichier)

# Question 5 : Sélectionner les colonnes quantitatives et calculer les paramètres
print("=== Question 5 : Calcul des paramètres statistiques ===")

# Sélectionner les colonnes quantitatives (int et float)
colonnes_quantitatives = []
for col in contenu.columns:
    if contenu[col].dtype in ['int64', 'float64']:
        colonnes_quantitatives.append(col)

print(f"Colonnes quantitatives sélectionnées : {colonnes_quantitatives}")
print("\n")

# Calculer les moyennes avec mean()
moyennes = []
for col in colonnes_quantitatives:
    moy = contenu[col].mean()
    moyennes.append(moy)

for col, moy in zip(colonnes_quantitatives, moyennes):
    print(f"{col} : {moy}")

# Calculer les médianes avec median()
medianes = []
for col in colonnes_quantitatives:
    med = contenu[col].median()
    medianes.append(med)

for col, med in zip(colonnes_quantitatives, medianes):
    print(f"{col} : {med}")

# Calculer les modes avec mode()
modes = []
for col in colonnes_quantitatives:
    mod = contenu[col].mode()
    # mode() retourne une série, on prend la première valeur
    if len(mod) > 0:
        modes.append(mod[0])
    else:
        modes.append(None)

for col, mod in zip(colonnes_quantitatives, modes):
    print(f"{col} : {mod}")

# Calculer l'écart type avec std()
ecarts_types = []
for col in colonnes_quantitatives:
    et = contenu[col].std()
    ecarts_types.append(et)

for col, et in zip(colonnes_quantitatives, ecarts_types):
    print(f"{col} : {et}")

# Calculer l'écart absolu à la moyenne avec abs() de Numpy
ecarts_absolus = []
for col in colonnes_quantitatives:
    moyenne = contenu[col].mean()
    ecart_abs = np.abs(contenu[col] - moyenne).mean()
    ecarts_absolus.append(ecart_abs)

for col, ea in zip(colonnes_quantitatives, ecarts_absolus):
    print(f"{col} : {ea}")

# Calculer l'étendue avec min() et max()
etendues = []
for col in colonnes_quantitatives:
    mini = contenu[col].min()
    maxi = contenu[col].max()
    etendue = maxi - mini
    etendues.append(etendue)

for col, et in zip(colonnes_quantitatives, etendues):
    print(f"{col} : {et}")

# Arrondir tous les paramètres à deux décimales avec round()
moyennes = [round(m, 2) if m is not None else None for m in moyennes]
medianes = [round(m, 2) if m is not None else None for m in medianes]
modes = [round(m, 2) if m is not None else None for m in modes]
ecarts_types = [round(e, 2) if e is not None else None for e in ecarts_types]
ecarts_absolus = [round(e, 2) if e is not None else None for e in ecarts_absolus]
etendues = [round(e, 2) if e is not None else None for e in etendues]

# Question 6 : Afficher la liste des paramètres
print("=== Question 6 : Affichage des paramètres ===")
print(f"Moyennes : {moyennes}")
print(f"Médianes : {medianes}")
print(f"Modes : {modes}")
print(f"Écarts types : {ecarts_types}")
print(f"Écarts absolus à la moyenne : {ecarts_absolus}")
print(f"Étendues : {etendues}")
print("\n")

#Je me permets d'afficher les valeurs dans un tableau afin de faciliter la lectuer

resultats = pd.DataFrame({
    "Colonne": colonnes_quantitatives,
    "Moyenne": moyennes,
    "Médiane": medianes,
    "Mode": modes,
    "Écart type": ecarts_types,
    "Écart absolu": ecarts_absolus,
    "Étendue": etendues
})

resultats

# Question 7 : Calculer la distance interquartile et interdécile avec quantile()
print("=== Question 7 : Distances interquartile et interdécile ===")

distances_interquartiles = []
distances_interdeciles = []

for col in colonnes_quantitatives:
    # Distance interquartile : Q3 - Q1
    q1 = contenu[col].quantile(0.25)
    q3 = contenu[col].quantile(0.75)
    diq = q3 - q1
    distances_interquartiles.append(round(diq, 2))

    # Distance interdécile : D9 - D1
    d1 = contenu[col].quantile(0.1)
    d9 = contenu[col].quantile(0.9)
    did = d9 - d1
    distances_interdeciles.append(round(did, 2))

print(f"Distances interquartiles : {distances_interquartiles}")
print(f"Distances interdéciles : {distances_interdeciles}")
print("\n")

# Question 8 : Faire des boîtes à moustache avec Matplotlib et une boucle
print("=== Question 8 : Création des boîtes à moustache ===")

import os
import matplotlib.pyplot as plt

print("=== Question 8 : Création des boîtes à moustache ===")

# Créer le dossier img
os.makedirs("./img", exist_ok=True)

for col in colonnes_quantitatives:
    plt.figure(figsize=(8, 6))
    plt.boxplot(contenu[col].dropna())
    plt.title(f'Boîte à moustache - {col}')
    plt.ylabel(col)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(f'./img/boxplot_{col.replace(" ", "_").replace("/", "-").replace("%", "pct")}.png')
    plt.show()

print(f"{len(colonnes_quantitatives)} boîtes à moustache créées dans ./img/")

# Question 9 : Charger le fichier island-index.csv
print("=== Question 9 : Chargement du fichier island-index.csv ===")
with open("./data/island-index.csv", "r", encoding="utf-8") as fichier:
    islands = pd.read_csv(fichier)
print("Fichier island-index.csv chargé")
print(islands.head())
print("\n")

# Question 10 : Catégoriser les îles par surface
print("=== Question 10 : Catégorisation des îles par surface ===")

# Sélectionner la colonne Surface (km²)
surfaces = islands['Surface (km²)']

# Définir les bornes des classes
bornes = [0, 10, 25, 50, 100, 2500, 5000, 10000, float('inf')]
labels = [
    ']0, 10]',
    ']10, 25]',
    ']25, 50]',
    ']50, 100]',
    ']100, 2500]',
    ']2500, 5000]',
    ']5000, 10000]',
    ']10000, +∞['
]

# Algorithme de catégorisation
compteurs = [0] * len(labels)

for surface in surfaces:
    if pd.notna(surface):  # Vérifier que la valeur n'est pas NaN
        if 0 < surface <= 10:
            compteurs[0] += 1
        elif 10 < surface <= 25:
            compteurs[1] += 1
        elif 25 < surface <= 50:
            compteurs[2] += 1
        elif 50 < surface <= 100:
            compteurs[3] += 1
        elif 100 < surface <= 2500:
            compteurs[4] += 1
        elif 2500 < surface <= 5000:
            compteurs[5] += 1
        elif 5000 < surface <= 10000:
            compteurs[6] += 1
        elif surface > 10000:
            compteurs[7] += 1

print("Nombre d'îles par catégorie de surface :")
for i, label in enumerate(labels):
    print(f"{label} km² : {compteurs[i]} îles")
print("\n")

# BONUS : Sortir les résultats au format CSV et Excel
print("=== BONUS : Export des résultats ===")

# Créer un DataFrame avec tous les paramètres calculés
resultats = pd.DataFrame({
    'Variable': colonnes_quantitatives,
    'Moyenne': moyennes,
    'Médiane': medianes,
    'Mode': modes,
    'Écart type': ecarts_types,
    'Écart absolu': ecarts_absolus,
    'Étendue': etendues,
    'Distance interquartile': distances_interquartiles,
    'Distance interdécile': distances_interdeciles
})

# Export CSV
resultats.to_csv('./parametres_statistiques.csv', index=False, encoding='utf-8')
print("Fichier CSV créé : parametres_statistiques.csv")

# Export Excel
resultats.to_excel('./parametres_statistiques.xlsx', index=False, engine='openpyxl')
print("Fichier Excel créé : parametres_statistiques.xlsx")

# Créer un DataFrame pour les catégories d'îles
categories_iles = pd.DataFrame({
    'Catégorie de surface (km²)': labels,
    'Nombre d\'îles': compteurs
})