# -*- coding: utf-8 -*-
"""Séance_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0Q9bq1poMFkTAlN7i8cRmeVHSrSSdVT
"""

#coding:utf8

import pandas as pd
import matplotlib.pyplot as plt

# Source des données : https://www.data.gouv.fr/datasets/election-presidentielle-des-10-et-24-avril-2022-resultats-definitifs-du-1er-tour/
with open("./data/resultats-elections-presidentielles-2022-1er-tour.csv","r",encoding="utf-8") as fichier:
    contenu = pd.read_csv(fichier)

# Mettre dans un commentaire le numéro de la question
# Question 1

#Question 5 : Afficher la méthode de Pandas DataFrame
print("=== Question 5 : Affichage avec DataFrame ===")
print(pd.DataFrame(contenu))
print("\n")

# Question 6 : Calculer avec len(...) le nombre de lignes et colonnes
print("=== Question 6 : Dimensions avec len() ===")
nb_lignes = len(contenu)
nb_colonnes = len(contenu.columns)
print(f"Nombre de lignes : {nb_lignes}")
print(f"Nombre de colonnes : {nb_colonnes}")
print("\n")

# Question 7 : Nature statistique des variables
# Métadonnées : https://www.data.gouv.fr/fr/datasets/r/9d45544a-1d29-4e7c-b0f0-f9e16d4531d4
types_colonnes = [
    ('Code du département', 'str'),
    ('Libellé du département', 'str'),
    ('Inscrits', 'int'),
    ('Abstentions', 'int'),
    ('% Abs/Ins', 'float'),
    ('Votants', 'int'),
    ('% Vot/Ins', 'float'),
    ('Blancs', 'int'),
    ('% Blancs/Ins', 'float'),
    ('% Blancs/Vot', 'float'),
    ('Nuls', 'int'),
    ('% Nuls/Ins', 'float'),
    ('% Nuls/Vot', 'float'),
    ('Exprimés', 'int'),
    ('% Exp/Ins', 'float'),
    ('% Exp/Vot', 'float'),
]
# Les colonnes candidats sont de type int (Voix) et float (%)
print("=== Question 7 : Types de variables ===")
for col, typ in types_colonnes:
    print(f"{col} : {typ}")
print("\n")

#Question 8 : Afficher avec head()
print("=== Question 8 : Noms des colonnes avec head() ===")
print(contenu.head())
print("\n")

#Question 9 : Sélectionner le nombre des inscrits
print("=== Question 9 : Sélection des inscrits ===")
inscrits = contenu['Inscrits']
print(inscrits)
print("\n")

#Question 10 : Calculer les effectifs de chaque colonne avec sum et append
print("=== Question 10 : Effectifs avec sum() et append() ===")
effectifs = []
types_dict = dict(types_colonnes)

for colonne in contenu.columns:
    # Condition : calculer uniquement pour int et float
    if colonne in types_dict:
        if types_dict[colonne] in ['int', 'float']:
            total = contenu[colonne].sum()
            effectifs.append(total)
            print(f"{colonne} : {total}")
    else:
        # Pour les colonnes candidats non listées
        if contenu[colonne].dtype in ['int64', 'float64']:
            total = contenu[colonne].sum()
            effectifs.append(total)
            print(f"{colonne} : {total}")
print("\n")

import os
# Créer le dossier pour les images
os.makedirs("./images", exist_ok=True)

# Question 11 : Diagrammes en barres pour inscrits et votant avec matplotlib et boucle
print("=== Question 11 : Diagrammes en barres ===")

# Boucle pour inscrits et votants
colonnes_a_tracer = ['Inscrits', 'Votants']
for col in colonnes_a_tracer:
    plt.figure(figsize=(15, 8))
    plt.bar(range(len(contenu)), contenu[col])
    plt.xlabel('Départements')
    plt.ylabel(f'Nombre de {col.lower()}')
    plt.title(f'{col} par département')
    plt.xticks(range(len(contenu)), contenu['Libellé du département'], rotation=90, fontsize=6)
    plt.tight_layout()
    plt.savefig(f'./images/{col.lower()}_par_departement.png')
    plt.close()
    print(f"Diagramme {col} créé")
print("\n")

# Question 12 : Diagrammes circulaires avec matplotlib et boucle
print("=== Question 12 : Diagrammes circulaires ===")

for i in range(len(contenu)):
    dept = contenu.iloc[i]['Libellé du département']
    valeurs = [
        contenu.iloc[i]['Blancs'],
        contenu.iloc[i]['Nuls'],
        contenu.iloc[i]['Exprimés'],
        contenu.iloc[i]['Abstentions']
    ]
    labels = ['Blancs', 'Nuls', 'Exprimés', 'Abstentions']

    plt.figure(figsize=(8, 8))
    plt.pie(valeurs, labels=labels, autopct='%1.1f%%')
    plt.title(f'Répartition des votes - {dept}')
    plt.tight_layout()
    nom_fichier = dept.replace(' ', '_').replace('/', '-').replace("'", '')
    plt.savefig(f'./images/repartition_{nom_fichier}.png')
    plt.show()

print(f"{len(contenu)} diagrammes circulaires créés")
print("\n")

# Question 13 : Histogramme avec matplotlib
print("=== Question 13 : Histogramme de distribution ===")
plt.figure(figsize=(10, 6))
# Histogramme avec density=True pour que la somme des surfaces = 1
n, bins, patches = plt.hist(contenu['Inscrits'], bins=20, density=True, edgecolor='black', alpha=0.7)
plt.xlabel('Nombre d\'inscrits')
plt.ylabel('Densité')
plt.title('Distribution des inscrits par département')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('./images/histogramme_inscrits.png')
plt.show()
print("Histogramme des inscrits créé")
somme_surfaces = sum(n[i] * (bins[i+1] - bins[i]) for i in range(len(n)))
print(f"Vérification : somme des surfaces = {somme_surfaces:.2f}")
print("\n")

# BONUS : Diagrammes circulaires par candidat
print("=== BONUS : Diagrammes circulaires par candidat ===")

# Identifier les colonnes avec "Voix" (candidats)
colonnes_candidats = [col for col in contenu.columns if 'Voix' in col and '%' not in col]

# Boucle pour chaque département
for i in range(len(contenu)):
    dept = contenu.iloc[i]['Libellé du département']
    valeurs_candidats = []
    labels_candidats = []

    for col in colonnes_candidats:
        valeurs_candidats.append(contenu.iloc[i][col])
        # Extraire le nom du candidat
        nom_candidat = col.split('Voix')[0].strip()
        labels_candidats.append(nom_candidat)

    plt.figure(figsize=(10, 10))
    plt.pie(valeurs_candidats, labels=labels_candidats, autopct='%1.1f%%')
    plt.title(f'Répartition des voix par candidat - {dept}')
    plt.tight_layout()
    nom_fichier = dept.replace(' ', '_').replace('/', '-').replace("'", '')
    plt.savefig(f'./images/candidats_{nom_fichier}.png')
    plt.close()

print(f"{len(contenu)} diagrammes par candidat créés")
print("\n")

# BONUS : Diagramme circulaire France entière
print("=== BONUS : Diagramme France entière ===")
voix_france = []
labels_france = []

for col in colonnes_candidats:
    total_voix = contenu[col].sum()
    voix_france.append(total_voix)
    nom_candidat = col.split('Voix')[0].strip()
    labels_france.append(nom_candidat)

plt.figure(figsize=(12, 12))
plt.pie(voix_france, labels=labels_france, autopct='%1.1f%%', startangle=90)
plt.title('Répartition des voix par candidat - France entière (1er tour 2022)')
plt.tight_layout()
plt.savefig('./images/candidats_France_entiere.png')
plt.show()
print("Diagramme France entière créé")
print("\n")

print("=== Traitement terminé ===")
print(f"Tous les graphiques ont été sauvegardés dans le dossier ./images/")